default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: karanmehta
  password: your_postgres_password

development:
  <<: *default
  database: my_poke_app_development

test:
  <<: *default
  database: my_poke_app_test

production:
  <<: *default
  database: my_poke_app_production
  username: karanmehta
  password: your_production_password
